#!/usr/bin/env node

const vfile = require('to-vfile');
const unified = require('unified');
const markdown = require('remark-parse');
const man = require('remark-man');
const {exec, spawn} = require('child_process');
const fs = require('fs');

const bookSrcDirectory = '../app/book/src';

function main () {
  if (process.argv.length < 3) return showUsage();

  const searchTerm = process.argv.slice(2).join(' ');

  searchForTerm(searchTerm, filename => {
    if (filename) showManPageForFile(filename);
  });
}

function searchForTerm(searchTerm, cb) {
  exec(`grep -irE '${searchTerm.replace(' ', '|')}' ${bookSrcDirectory}/*.md`, {maxBuffer: 1024 * 1024 * 500}, (err, stdout) => {
    if (err) {
      console.log(`No results for "${searchTerm}"`);
      return;
    }

    const outputLines = stdout.split('\n');
    const occurrenceCounts = outputLines.reduce((acc, line) => {
      const filename = line.split(':')[0];

      return {
        ...acc,
        [filename]: acc[filename] ? acc[filename] + 1 : 1
      };
    }, {});

    let maxCount = 0, maxFilename;
    Object.keys(occurrenceCounts).forEach(filename => {
      if (maxCount < occurrenceCounts[filename]) {
        maxCount = occurrenceCounts[filename];
        maxFilename = filename;
      }
    });

    return cb(maxFilename);
  });
}

async function showManPageForFile (filename) {
  let manFile;

  await unified()
    .use(markdown)
    .use(man)
    .process(vfile.readSync(filename), function(err, file) {
      if (err) throw err;
      file.extname = '.1';
      vfile.writeSync({...file, dirname: '/tmp'});
      manFile = '/tmp/' + file.basename;
    });

  spawn('man', [manFile], { stdio: ['ignore', 1, 2] });
}

function showUsage () {
  const usage = [
    '',
    'Usage:  mantw <search term>',
    '',
    'Search the Tailwind docs and show the top result as a man page',
    ''
  ].join('\n');

  console.log(usage);
}

main();
